export const ALERT = {
  SET_ALERT: 'SET_ALERT',
  UNSET_ALERT: 'UNSET_ALERT',
};

export const USER = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
};

export const TASK = {
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_FAILURE: 'CREATE_TASK_FAILURE',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_FAILURE: 'GET_TASKS_FAILURE',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_FAILURE: 'DELETE_TASK_FAILURE',
};

export const PROFILE = {
  UPLOAD_PROFILE_SUCCESS: 'UPLOAD_PROFILE_SUCCESS',
  UPLOAD_PROFILE_FAILURE: 'UPLOAD_PROFILE_FAILURE',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  UPLOAD_PICTURE_SUCCESS: 'UPLOAD_PICTURE_SUCCESS',
  UPLOAD_PICTURE_FAILURE: 'UPLOAD_PICTURE_FAILURE',
};
